export { useModal } from "./useModal";
export { useCheckIsValidKeyCap } from "./useCheckIsValidKeyCap";
export { useFindPositionToAddLetter } from "./useFindPositionToAddLetter";
export { useCheckLettersStatus } from "./useCheckLettersStatus";
export { useCheckIsCorrectWord } from "./useCheckIsCorrectWord";
export { useCheckIsLoser } from "./useCheckIsLoser";
export { useFindPositionToDeleteLetter } from "./useFindPositionToDeleteLetter";
export { useCreateTimeToNewWord } from "./useCreateTimeToNewWord";
export { useCalculateTimeLeft } from "./useCalculateTimeLeft";
